
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jgranados.jflex_cup.sumas.parser;

import java_cup.runtime.*;
import com.jgranados.jflex_cup.sumas.lexer.SumasLexer;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SumasParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SumasParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SumasParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SumasParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\005\000\002\003\003\000\002\002\004\000\002\002" +
    "\005\000\002\002\007\000\002\002\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\013\000\006\003\005\006\007\001\002\000\004\002" +
    "\015\001\002\000\006\003\005\006\007\001\002\000\004" +
    "\002\001\001\002\000\004\004\010\001\002\000\004\006" +
    "\011\001\002\000\006\002\uffff\005\012\001\002\000\006" +
    "\003\005\006\007\001\002\000\004\002\ufffe\001\002\000" +
    "\004\002\ufffd\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\013\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\004\002\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\002" +
    "\012\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SumasParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SumasParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SumasParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        
    public SumasParser(SumasLexer lexer) {
        super(lexer);
    }

    private int count = 0;

    private void increaseCount() {
        count++;
    }
    
    public int getCount() {
        return count;
    }


    public void report_error(String message, Object info) {
        System.out.println("public void report_error");
    }
    
    public void report_fatal_error(String message, Object info) {
        System.out.println("public void report_fatal_error");
    }

    public void syntax_error(Symbol cur_token) {
        System.out.println("El error es el simbolo: " + sym.terminalNames[cur_token.sym]);
        System.out.println(String.format("En la posicion: %d, %d", cur_token.left, cur_token.right));
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
        if (cur_token.sym == sym.EOF) {
            System.out.println("public void unrecoveredsyntax_error");
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SumasParser$actions {
  private final SumasParser parser;

  /** Constructor */
  CUP$SumasParser$actions(SumasParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SumasParser$do_action_part00000000(
    int                        CUP$SumasParser$act_num,
    java_cup.runtime.lr_parser CUP$SumasParser$parser,
    java.util.Stack            CUP$SumasParser$stack,
    int                        CUP$SumasParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SumasParser$result;

      /* select the action based on the action number */
      switch (CUP$SumasParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // a ::= s 
            {
              Object RESULT =null;
		int sumasleft = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()).left;
		int sumasright = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()).right;
		String sumas = (String)((java_cup.runtime.Symbol) CUP$SumasParser$stack.peek()).value;
		 System.out.println(sumas);  
              CUP$SumasParser$result = parser.getSymbolFactory().newSymbol("a",1, ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()), RESULT);
            }
          return CUP$SumasParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= a EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-1)).value;
		RESULT = start_val;
              CUP$SumasParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-1)), ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SumasParser$parser.done_parsing();
          return CUP$SumasParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // s ::= ENTERO MAS ENTERO 
            {
              String RESULT =null;
		int entero1left = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-2)).left;
		int entero1right = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-2)).right;
		Integer entero1 = (Integer)((java_cup.runtime.Symbol) CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-2)).value;
		int entero2left = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()).left;
		int entero2right = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()).right;
		Integer entero2 = (Integer)((java_cup.runtime.Symbol) CUP$SumasParser$stack.peek()).value;
		 increaseCount(); RESULT = String.format("La suma es: %d", entero1 + entero2); /*System.out.println(String.format("La suma es: %d", entero1 + entero2));*/ 
              CUP$SumasParser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-2)), ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()), RESULT);
            }
          return CUP$SumasParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // s ::= ENTERO MAS ENTERO COMA s 
            {
              String RESULT =null;
		int entero1left = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-4)).left;
		int entero1right = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-4)).right;
		Integer entero1 = (Integer)((java_cup.runtime.Symbol) CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-4)).value;
		int entero2left = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-2)).left;
		int entero2right = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-2)).right;
		Integer entero2 = (Integer)((java_cup.runtime.Symbol) CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-2)).value;
		int sumaPrevleft = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()).left;
		int sumaPrevright = ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()).right;
		String sumaPrev = (String)((java_cup.runtime.Symbol) CUP$SumasParser$stack.peek()).value;
		 
                                                                increaseCount();
                                                                String suma = String.format("La suma es: %d", entero1 + entero2);
                                                                String sumas = suma + "\n" + sumaPrev;
                                                                
                                                                RESULT = sumas;
                                                                /*System.out.println(String.format("La suma es: %d", entero1 + entero2));*/
                                                             
              CUP$SumasParser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-4)), ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()), RESULT);
            }
          return CUP$SumasParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // s ::= error s 
            {
              String RESULT =null;
		 System.out.println("accion desde gramatica"); 
              CUP$SumasParser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$SumasParser$stack.elementAt(CUP$SumasParser$top-1)), ((java_cup.runtime.Symbol)CUP$SumasParser$stack.peek()), RESULT);
            }
          return CUP$SumasParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SumasParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SumasParser$do_action(
    int                        CUP$SumasParser$act_num,
    java_cup.runtime.lr_parser CUP$SumasParser$parser,
    java.util.Stack            CUP$SumasParser$stack,
    int                        CUP$SumasParser$top)
    throws java.lang.Exception
    {
              return CUP$SumasParser$do_action_part00000000(
                               CUP$SumasParser$act_num,
                               CUP$SumasParser$parser,
                               CUP$SumasParser$stack,
                               CUP$SumasParser$top);
    }
}

}